print('='*30)
char1 = str(input('Digite alguma coisa: '))
print('{} é alfa - numerico?' .format(char1),char1.isalnum())
print('{} é alfabético?' .format(char1),char1.isalpha())
#print('{} é da tabela ASCII?' .format(char1),char1.isacii())
print('{} é decimal?' .format(char1),char1.isdecimal())
print('{} é um dígito?' .format(char1),char1.isdigit())
print('{} toda os caracteres são minúsculos?' .format(char1),char1.islower())
print('{} é um numero?' .format(char1),char1.isnumeric())
print('{} pode ser impresso na tela?' .format(char1),char1.isprintable())
print('\n\t\t\tACABOOOU')
print('='*30)